apiVersion: v1
kind: Service
metadata:
  name: hct-frontend-service
  namespace: hct-frontend
spec:
  selector:
    app: hct-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer