apiVersion: v1
kind: Secret
metadata:
  name: hct-cliente-secret
  namespace: hct-cliente
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9tYXJjb1VzZXI6aW5mYW50ZTk4MzQ0NzE5NkBjbHVzdGVyMC5reDNmYXRxLm1vbmdvZGIubmV0L21zLWNsaWVudGU=