server:
  port: 8083

spring:
  application:
    name: hct-alquiler
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://marcoUser:infante983447196@cluster0.kx3fatq.mongodb.net/ms-alquiler}

services:
  vehiculo:
    url: ${VEHICULO_URL:http://localhost:8081}
  cliente:
    url: ${CLIENTE_URL:http://localhost:8082}