apiVersion: v1
kind: Service
metadata:
  name: hct-alquiler-service
  namespace: hct-alquiler
spec:
  selector:
    app: hct-alquiler
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP